version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - regov_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - regov
  
  redis: 
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - regov

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fastapi
  #   restart: always
  #   platform: linux/amd64 #for platform error on Apple M1 chips
  #   env_file: .env
  #   command: bash -c "
  #       alembic upgrade head
  #       && gunicorn --config ./gunicorn.conf.py app.main:app"
  #   ports:
  #     - 80:8000
  #   depends_on:
  #     - postgres
  #   networks:
  #     - regov

volumes:
  regov_data:

networks:
  regov:
    name: regov
    driver: bridge
