"""init regov database

Revision ID: f88f03273d16
Revises: 
Create Date: 2023-04-03 17:03:51.609519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88f03273d16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('id_number', sa.String(
                        length=255), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('phone_number', sa.String(
                        length=255), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['patients.id'], name=op.f(
                        'fk_patients_parent_id_patients')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
                    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('username', sa.String(
                        length=255), nullable=False),
                    sa.Column('password', sa.String(
                        length=255), nullable=False),
                    sa.Column('patient_id', sa.Integer(), nullable=True),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f(
                        'fk_users_patient_id_patients')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
