"""Create admin
Revision ID: f88f03273d19
Revises: 
Create Date: 2023-04-03 17:03:51.609519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88f03273d19'
down_revision = "f88f03273d16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""INSERT INTO "public"."users" ("id", "is_admin", "username", "password", "patient_id", "created_date", "updated_date")
        VALUES (1, true, 'admin@gmail.com', '$2b$12$kh.txMDWzUc2nFTek55O8.6VTSo2.BUO20eajO01Zhg94JqzR.FrK', null, '2023-04-04', null) ON CONFLICT DO NOTHING;"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
